// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoldLabel: typeof import('./src/components/BoldLabel.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    IRiEdit2Line: typeof import('~icons/ri/edit2-line')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    MainContainer: typeof import('./src/components/MainContainer.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
  }
}
