/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoldLabel: typeof import('./src/components/BoldLabel.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    GithubBtn: typeof import('./src/components/GithubBtn.vue')['default']
    IMdiTranslate: typeof import('~icons/mdi/translate')['default']
    IRiEdit2Line: typeof import('~icons/ri/edit2-line')['default']
    IRiGithubFill: typeof import('~icons/ri/github-fill')['default']
    IRiMoonLine: typeof import('~icons/ri/moon-line')['default']
    IRiSunLine: typeof import('~icons/ri/sun-line')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    MainContainer: typeof import('./src/components/MainContainer.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
  }
}
