// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import { inject, ref } from 'vue';
import { initI18nVuePlugin } from 'typesafe-i18n/vue';
import { loadedFormatters, loadedLocales } from './i18n-util.js';
var _a = initI18nVuePlugin(inject, ref, loadedLocales, loadedFormatters), typesafeI18n = _a.typesafeI18n, i18nPlugin = _a.i18nPlugin;
export { typesafeI18n, i18nPlugin };
