// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh-cn'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * O​n​l​i​n​e​ ​E​x​c​e​l​ ​C​o​l​u​m​n​ ​C​o​n​v​e​r​t​e​r
	 */
	title: string
	/**
	 * C​o​n​v​e​r​t​ ​C​o​l​u​m​n​ ​N​a​m​e​ ​t​o​ ​N​u​m​b​e​r
	 */
	nameToNumber: string
	/**
	 * C​o​n​v​e​r​t​ ​N​u​m​b​e​r​ ​t​o​ ​C​o​l​u​m​n​ ​N​a​m​e
	 */
	numberToName: string
	/**
	 * E​x​c​e​l​ ​C​o​l​u​m​n​ ​N​a​m​e
	 */
	excelColumnName: string
	/**
	 * C​o​n​v​e​r​t​e​d​ ​N​u​m​b​e​r
	 */
	convertedNumber: string
	/**
	 * E​x​c​e​l​ ​C​o​l​u​m​n​ ​N​u​m​b​e​r
	 */
	excelColumnNumber: string
	/**
	 * C​o​n​v​e​r​t​e​d​ ​N​a​m​e
	 */
	convertedName: string
	/**
	 * M​u​l​t​i​p​l​e​ ​E​x​c​e​l​ ​C​o​l​u​m​n​ ​N​a​m​e​ ​C​o​n​v​e​r​t​e​r
	 */
	multiNameConverter: string
	/**
	 * T​o​ ​c​o​n​v​e​r​t​ ​b​a​c​k​ ​a​n​d​ ​f​o​r​t​h​ ​c​o​r​r​e​c​t​l​y​,​ ​c​o​l​u​m​n​ ​n​a​m​e​ ​s​h​o​u​l​d​ ​<​=​ ​Z​Z​Z​Z​Z​Z​ ​a​n​d​ ​c​o​l​u​m​n​ ​n​u​m​b​e​r​ ​s​h​o​u​l​d​ ​<​=​ ​3​2​1​2​7​2​4​0​6
	 */
	excelBatchConvertDesc: string
	/**
	 * C​o​n​v​e​r​t​ ​t​o​ ​N​u​m​b​e​r​s​ ​=​>
	 */
	convertNameToNum: string
	/**
	 *  ​<​=​ ​C​o​n​v​e​r​t​ ​t​o​ ​N​a​m​e​s
	 */
	convertNumToName: string
}

export type TranslationFunctions = {
	/**
	 * Online Excel Column Converter
	 */
	title: () => LocalizedString
	/**
	 * Convert Column Name to Number
	 */
	nameToNumber: () => LocalizedString
	/**
	 * Convert Number to Column Name
	 */
	numberToName: () => LocalizedString
	/**
	 * Excel Column Name
	 */
	excelColumnName: () => LocalizedString
	/**
	 * Converted Number
	 */
	convertedNumber: () => LocalizedString
	/**
	 * Excel Column Number
	 */
	excelColumnNumber: () => LocalizedString
	/**
	 * Converted Name
	 */
	convertedName: () => LocalizedString
	/**
	 * Multiple Excel Column Name Converter
	 */
	multiNameConverter: () => LocalizedString
	/**
	 * To convert back and forth correctly, column name should <= ZZZZZZ and column number should <= 321272406
	 */
	excelBatchConvertDesc: () => LocalizedString
	/**
	 * Convert to Numbers =>
	 */
	convertNameToNum: () => LocalizedString
	/**
	 *  <= Convert to Names
	 */
	convertNumToName: () => LocalizedString
}

export type Formatters = {}
