// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import { initFormatters } from './formatters.js';
import { loadedFormatters, loadedLocales, locales } from './i18n-util.js';
import en from './en/index.js';
import zh_cn from './zh-cn/index.js';
var localeTranslations = {
    en: en,
    'zh-cn': zh_cn,
};
export var loadLocale = function (locale) {
    if (loadedLocales[locale])
        return;
    loadedLocales[locale] = localeTranslations[locale];
    loadFormatters(locale);
};
export var loadAllLocales = function () { return locales.forEach(loadLocale); };
export var loadFormatters = function (locale) {
    return void (loadedFormatters[locale] = initFormatters(locale));
};
